name: CartCleaner
main: com.github.CubieX.CartCleaner.CartCleaner
version: 1.0.1
authors: [CubieX]
description: Removes Carts if player exits them while not resting on a unpowered PoweredRail. 

commands:
    cc:
      description: Using CartCleaner
      usage: /cc version

permissions:
    cartcleaner.admin:
        description: Allows use of all commands
        default: op